version: '1'

services:
  react:
    build: 
      context: ./app-ui
    ports:
      - "3000:3000"
    volumes:
      - ./app-ui:/usr/src/app

  node:
    build: 
      context: ./app-api
    ports:
      - "3001:3001"
    volumes:
      - ./app-api:/usr/src/app

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  